version: '3'

services:

  order-service:
    build:
      context: ./fastapi-order-service
    ports:
      - 8888:8888
    volumes:
      - ./fastapi-order-service/app:/src:Z
    command: >
      sh -c 'uvicorn --factory main:create_app --host 0.0.0.0 --port 8888 --reload'

  database:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./postgres_restore:/restore"
      - "./postgres_data:/var/lib/postgresql/data/pgdata"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - PGDATA=/var/lib/postgresql/data/pgdata

  product-service:
    image: rodolpheche/wiremock:2.23.2-alpine
    command: --verbose
    volumes:
      - ./wiremock/product-service/stubs:/home/wiremock
    ports:
    - "8081:8080"

  user-service:
    image: rodolpheche/wiremock:2.23.2-alpine
    command: --verbose
    volumes:
      - ./wiremock/user-service/stubs:/home/wiremock
    ports:
    - "8082:8080"

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=brokeruser
      - RABBITMQ_DEFAULT_PASS=brokerpass
    ports:
      - "5672:5672"
      - "15672:15672"
